FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        libgomp1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
        pandas \
        numpy \
        scikit-learn \
        pyarrow \
        joblib \
        psutil \
        lightgbm

WORKDIR /workspace
CMD ["bash"]
